### ISSUE TITLE
Code examples 

### ISSUE THREAD

**Issue by scottybo** [ZiNETHQ/spark-roles#10]
Are there any code examples for detecting user and team roles / permissions in blades, controllers, middleware etc? Also any examples of permission priority? Eg. if a team allows permission X but a specific user is not allowed this permission, how does this get handled? 

We're looking to implement this on our system and I was hoping we could get some more in depth docs.

**Comment by drjonnicholson** [comment]
Hi @scottybo,

Is the wiki sufficient documentation? Eg https://github.com/ZiNETHQ/spark-roles/wiki/Template-Helpers.

If not I can possibly help out.

As for permission priority, I do t think that’s something we handle, interesting idea though. I don’t think we have a concept of denying permissions, ie it’s all additive at the moment. A user has the permissions of their team and then themselves. We typically use this in the case of a logged in user in which case the team is always their current team.
