### ISSUE TITLE
How do use Role Scope, is this table usable or not yet?

### ISSUE THREAD

**Issue by codeitlikemiley** [ZiNETHQ/spark-roles#5]
Seems lIke an application of roles with polymorphism of any model...
can you tell me if how this works and is this already on the package or not yet ty

**Comment by drjonnicholson** [comment]
The package implicitly depends on Laravel Spark (https://spark.laravel.com/), and the team/user model that's set up there. If you're looking for a package like this, but one that's not expecting to work within the Laravel Spark ecosystem, then I recommend caffeinated/shinobi (https://github.com/caffeinated/shinobi), where this project was originally forked from.

There is some documentation int he readme and on the Wiki (https://github.com/ZiNETHQ/spark-roles/wiki).

This works, we are using it in our applications. We have delayed making an official release on Packagist whilst we iron out bugs as we find them as we develop our other products. We are close to releasing those so we should be making a versioned release of this in the next few weeks.

**Comment by drjonnicholson** [comment]
I'm going to close this as it's not a code issue. Feel free to ask any further questions though.
