### ISSUE TITLE
SparkRoles fasade points to the wrong location

### ISSUE THREAD

**Issue by KimKJDesigns** [ZiNETHQ/spark-roles#8]
As the title states, the SparkRoles fasade points to the following, as per installation instructions

`'SparkRoles' => ZiNETHQ\SparkRoles\Facades\SparkRolesShinobi::class,`

however, it should be 

`'SparkRoles' => ZiNETHQ\SparkRoles\Facades\SparkRoles::class,`

**Comment by drjonnicholson** [comment]
Thanks for pointing this out! I’ve just fixed it on the Wiki page.
